[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "backend"
source = "backend"

[services.variables]
NODE_ENV = "production"
PORT = "${{RAILWAY_PORT}}"

[[services]]
name = "frontend" 
source = "."

[services.variables]
VITE_API_BASE_URL = "${{backend.RAILWAY_PUBLIC_DOMAIN}}"
