services:
  # Backend Service
  - type: web
    name: sustainable-living-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    env: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: CLIENT_URL
        value: https://sustainable-living-frontend.onrender.com

  # Frontend Service  
  - type: web
    name: sustainable-living-frontend
    runtime: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    env: node
    envVars:
      - key: VITE_API_BASE_URL
        value: https://sustainable-living-backend.onrender.com

  # MongoDB Database
  - type: web
    name: mongodb
    runtime: docker
    plan: free
    dockerfilePath: ./mongo.Dockerfile
