# Render deployment configuration
# Copy this to render.yaml in your root directory if needed

services:
  - type: web
    name: sustainable-living-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: CLIENT_URL
        value: https://sustainable-living-frontend.onrender.com
      - key: PORT
        value: 10000
    rootDir: backend
